// Package compilation implements zsh file compilation during sync.
package compilation

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"goodkind.io/.dotfiles/internal/cmdexec"
	"goodkind.io/.dotfiles/internal/prefercache"
	"goodkind.io/.dotfiles/internal/runner"
	"goodkind.io/.dotfiles/internal/sync/common"
	"goodkind.io/.dotfiles/internal/telemetry"
	"gopkg.in/yaml.v3"
)

const (
	// AgentSourceDirName is the name of the agent source directory within dotfiles.
	AgentSourceDirName = ".agents"
	// CursorCompatibilityDirName is the legacy cursor directory name used as a compatibility symlink target.
	CursorCompatibilityDirName = ".cursor"
	// GeneratedAgentMarker is the plain-text marker embedded in files generated from .agents.
	GeneratedAgentMarker = "# Generated by dotfiles from .agents. Do not edit this file directly."
	// GeneratedAgentHTMLMarker is the HTML comment marker embedded in files generated from .agents.
	GeneratedAgentHTMLMarker = "<!-- Generated by dotfiles from .agents. Do not edit this file directly. -->"
	// GeneratedCursorMarker is the HTML comment marker embedded in files generated from .cursor.
	GeneratedCursorMarker = "<!-- Generated by dotfiles from .cursor. Do not edit this file directly. -->"
)

// AgentSourcePaths holds resolved paths for the agent source directory tree.
type AgentSourcePaths struct {
	Root     string
	Rules    string
	Commands string
	Skills   string
}

type agentRuleFrontmatter struct {
	Description string `yaml:"description,omitempty"`
	Globs       string `yaml:"globs,omitempty"`
	AlwaysApply bool   `yaml:"alwaysApply,omitempty"`
}

type frontmatterMetadata struct {
	Name        string `yaml:"name,omitempty"`
	Description string `yaml:"description,omitempty"`
	ApplyTo     string `yaml:"applyTo,omitempty"`
}

// ResolveAgentSource returns the AgentSourcePaths for the given dotfiles root.
func ResolveAgentSource(dotfiles string) AgentSourcePaths {
	root := filepath.Join(dotfiles, AgentSourceDirName)
	if _, err := os.Stat(root); err != nil {
		compatibilityRoot := filepath.Join(dotfiles, CursorCompatibilityDirName)
		if _, compatibilityErr := os.Stat(compatibilityRoot); compatibilityErr == nil {
			root = compatibilityRoot
		}
	}

	return AgentSourcePaths{
		Root:     root,
		Rules:    filepath.Join(root, "rules"),
		Commands: filepath.Join(root, "commands"),
		Skills:   filepath.Join(root, "skills"),
	}
}

// EnsureCursorCompatibilityLink ensures .cursor is a symlink pointing to .agents.
func EnsureCursorCompatibilityLink(dotfiles string) error {
	agentsRoot := filepath.Join(dotfiles, AgentSourceDirName)
	if _, err := os.Stat(agentsRoot); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: stat failed", "path", agentsRoot, "err", err)
		return fmt.Errorf("stat %s: %w", agentsRoot, err)
	}

	cursorPath := filepath.Join(dotfiles, CursorCompatibilityDirName)
	info, err := os.Lstat(cursorPath)
	if err != nil {
		if os.IsNotExist(err) {
			if symlinkErr := os.Symlink(AgentSourceDirName, cursorPath); symlinkErr != nil {
				return fmt.Errorf("creating symlink %s: %w", cursorPath, symlinkErr)
			}
			return nil
		}
		return fmt.Errorf("stat %s: %w", cursorPath, err)
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return fmt.Errorf("%s exists and is not a symlink", cursorPath)
	}

	linkTarget, err := os.Readlink(cursorPath)
	if err != nil {
		return fmt.Errorf("reading symlink %s: %w", cursorPath, err)
	}
	if !filepath.IsAbs(linkTarget) {
		linkTarget = filepath.Join(filepath.Dir(cursorPath), linkTarget)
	}
	if filepath.Clean(linkTarget) != filepath.Clean(agentsRoot) {
		return fmt.Errorf("%s points to %s, expected %s", cursorPath, linkTarget, agentsRoot)
	}
	return nil
}

// HasGeneratedMarker reports whether content contains any generated-file marker.
func HasGeneratedMarker(content string) bool {
	return strings.Contains(content, GeneratedAgentMarker) || strings.Contains(content, GeneratedAgentHTMLMarker) || strings.Contains(content, GeneratedCursorMarker)
}

// CompileZshFiles compiles all .zsh files found under standard dotfiles directories.
func CompileZshFiles(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	dirs := []string{
		filepath.Join(dotfiles, "zshrc"),
		filepath.Join(dotfiles, "lib", "zinit"),
		filepath.Join(dotfiles, "lib", "zsh-defer"),
		filepath.Join(dotfiles, "home"),
		filepath.Join(dotfiles, "bin"),
	}
	for _, dir := range dirs {
		_ = filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			name := filepath.Base(path)
			if !strings.HasSuffix(name, ".zsh") && name != ".zshrc" {
				return nil
			}
			compiled := path + ".zwc"
			if NeedsCompile(path, compiled) {
				_ = cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", fmt.Sprintf("zcompile %q", path))
			}
			return nil
		})
	}
	return nil
}

// NeedsCompile reports whether source is newer than target and requires recompilation.
func NeedsCompile(source string, target string) bool {
	sourceInfo, err := os.Stat(source)
	if err != nil {
		return false
	}
	targetInfo, err := os.Stat(target)
	if err != nil {
		return true
	}
	return sourceInfo.ModTime().After(targetInfo.ModTime())
}

// RebuildZcompdump removes and regenerates the zsh completion dump file.
func RebuildZcompdump(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	slog.InfoContext(ctx, "compilation: RebuildZcompdump")
	_ = os.RemoveAll(filepath.Clean(filepath.Join(os.Getenv("HOME"), ".zcompdump")))
	if !runner.HasCommand("zsh") {
		return nil
	}
	fpath := filepath.Join(dotfiles, "zshrc", "completions")
	zcompdump := "~/.zcompdump"
	autoloadCmd := fmt.Sprintf("fpath=(\"%s\" $fpath)\nautoload -Uz compinit\n", fpath)
	if err := cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", autoloadCmd+"compinit -d "+zcompdump+"\nzcompile "+zcompdump+"\n"); err != nil {
		slog.ErrorContext(ctx, "rebuild zsh completions", "err", err)
		return fmt.Errorf("rebuild zsh completions: %w", err)
	}
	return nil
}

// RebuildPreferCache rebuilds the prefer-alias cache for the dotfiles installation.
func RebuildPreferCache(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	if err := prefercache.Rebuild(ctx, dotfiles, false, logger); err != nil {
		slog.WarnContext(ctx, "compilation: RebuildPreferCache failed", "err", err)
		return fmt.Errorf("rebuilding prefer cache: %w", err)
	}
	return nil
}

// CreateHushLogin creates the ~/.hushlogin file if it does not already exist.
func CreateHushLogin(ctx context.Context, _ *telemetry.Logger) error {
	path := filepath.Join(os.Getenv("HOME"), ".hushlogin")
	if _, err := os.Stat(filepath.Clean(path)); err == nil {
		return nil
	}
	if err := common.Touch(path); err != nil {
		slog.WarnContext(ctx, "compilation: CreateHushLogin touch failed", "err", err)
		return fmt.Errorf("creating hushlogin: %w", err)
	}
	return nil
}

// SyncRulesFromDir copies .mdc rule files from src into dst as symlinks.
func SyncRulesFromDir(src string, dst string) error {
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncRulesFromDir stat failed", "src", src, "err", err)
		return fmt.Errorf("stat %s: %w", src, err)
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	entries, err := filepath.Glob(filepath.Join(src, "*.mdc"))
	if err != nil {
		return fmt.Errorf("globbing files in %s: %w", src, err)
	}
	for _, file := range entries {
		target := filepath.Join(dst, filepath.Base(file))
		if err := SyncFile(file, target); err != nil {
			return err
		}
	}
	return nil
}

// SyncRulesFromDirAsMd copies .mdc rule files from src into dst renaming them to .md.
func SyncRulesFromDirAsMd(src string, dst string) error {
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncRulesFromDirAsMd stat failed", "src", src, "err", err)
		return fmt.Errorf("stat %s: %w", src, err)
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	entries, err := filepath.Glob(filepath.Join(src, "*.mdc"))
	if err != nil {
		return fmt.Errorf("globbing files in %s: %w", src, err)
	}
	for _, file := range entries {
		base := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		target := filepath.Join(dst, base+".md")
		if err := SyncFile(file, target); err != nil {
			return err
		}
	}
	return nil
}

// RenderRulesAsInstructionDoc concatenates .mdc rule files from src into a single markdown document at dst.
func RenderRulesAsInstructionDoc(src string, dst string, title string) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return nil
	}

	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	builder.WriteString(GeneratedAgentHTMLMarker)
	builder.WriteString("\n\n")

	for index, file := range files {
		if index > 0 {
			builder.WriteString("\n\n")
		}
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		builder.WriteString("## ")
		builder.WriteString(baseName)
		builder.WriteString("\n\n")

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderRulesAsInstructionDoc read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		body, stripErr := stripFrontmatter(string(content))
		if stripErr != nil {
			return stripErr
		}
		body = strings.TrimSpace(body)
		builder.WriteString(body)
		builder.WriteString("\n")
	}

	return writeFileIfChanged(dst, []byte(builder.String()))
}

// RenderCopilotInstructionFiles renders .mdc rule files from src as .instructions.md files in dst.
func RenderCopilotInstructionFiles(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		slog.Warn("compilation: RenderCopilotInstructionFiles mkdir failed", "dst", dst, "err", err)
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}

	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := baseName + ".instructions.md"
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderCopilotInstructionFiles read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		frontmatter, body, parseErr := parseFrontmatter(string(content))
		if parseErr != nil {
			return parseErr
		}
		rendered, renderErr := renderCopilotInstruction(baseName, frontmatter, body)
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(dst, targetName), []byte(rendered)); err != nil {
			return err
		}
	}

	return removeMissingManagedFiles(dst, ".instructions.md", activeFiles)
}

// RenderCopilotPromptFiles renders .md command files from src as .prompt.md files in dst.
func RenderCopilotPromptFiles(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".md")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		slog.Warn("compilation: render prompt files mkdir failed", "err", err)
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}

	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := baseName + ".prompt.md"
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: render prompt file read failed", "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		rendered, renderErr := renderCopilotPrompt(baseName, string(content))
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(dst, targetName), []byte(rendered)); err != nil {
			return err
		}
	}

	return removeMissingManagedFiles(dst, ".prompt.md", activeFiles)
}

// RenderCodexRules concatenates .rules files from src into a single Codex rules file at dst.
func RenderCodexRules(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".rules")
	if err != nil {
		return err
	}

	var builder strings.Builder
	builder.WriteString(GeneratedAgentMarker)
	builder.WriteString("\n")
	for _, file := range files {
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderCodexRules read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		trimmedContent := strings.TrimSpace(string(content))
		if trimmedContent == "" {
			continue
		}
		builder.WriteString("\n# ")
		builder.WriteString(filepath.Base(file))
		builder.WriteString("\n")
		builder.WriteString(trimmedContent)
		builder.WriteString("\n")
	}
	return writeFileIfChanged(dst, []byte(builder.String()))
}

// SyncCommandFilesAsSkillDirs converts .md command files from src into skill directories under dst.
func SyncCommandFilesAsSkillDirs(src string, dst string, managedPrefix string) error {
	files, err := sortedFilesWithExt(src, ".md")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		slog.Warn("compilation: SyncCommandFilesAsSkillDirs mkdir failed", "dst", dst, "err", err)
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}

	activeDirs := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		dirName := managedPrefix + baseName
		activeDirs[dirName] = struct{}{}

		targetDir := filepath.Join(dst, dirName)
		if err := os.MkdirAll(targetDir, 0o755); err != nil {
			slog.Warn("compilation: SyncCommandFilesAsSkillDirs mkdir target failed", "targetDir", targetDir, "err", err)
			return fmt.Errorf("creating directory %s: %w", targetDir, err)
		}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: SyncCommandFilesAsSkillDirs read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		skillContent, renderErr := renderCommandAsSkill(baseName, string(content))
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(targetDir, "SKILL.md"), []byte(skillContent)); err != nil {
			return err
		}
	}

	return removeMissingManagedSkillDirs(dst, managedPrefix, activeDirs)
}

// SyncFilesToDir copies all files from src into dst as symlinks.
func SyncFilesToDir(src string, dst string) error {
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncFilesToDir stat failed", "src", src, "err", err)
		return fmt.Errorf("stat %s: %w", src, err)
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	entries, err := os.ReadDir(src)
	if err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncFilesToDir ReadDir failed", "src", src, "err", err)
		return fmt.Errorf("read dir %s: %w", src, err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if err := SyncFile(filepath.Join(src, entry.Name()), filepath.Join(dst, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

// SyncSkillDirs copies skill subdirectories from src into dst as symlinks.
func SyncSkillDirs(src string, dst string) error {
	slog.Info("compilation: SyncSkillDirs")
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncSkillDirs stat failed", "src", src, "err", err)
		return fmt.Errorf("stat %s: %w", src, err)
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	entries, err := os.ReadDir(src)
	if err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: SyncSkillDirs ReadDir failed", "src", src, "err", err)
		return fmt.Errorf("read dir %s: %w", src, err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		source := filepath.Join(src, entry.Name())
		target := filepath.Join(dst, entry.Name())
		if sameFile(source, target) && !isSymlink(target) {
			continue
		}
		if common.IsSymlinkTo(target, source) {
			continue
		}
		_ = os.Remove(target)
		if err := os.Symlink(source, target); err != nil {
			return fmt.Errorf("creating symlink %s: %w", target, err)
		}
	}
	return nil
}

// SyncFile creates a symlink at dst pointing to src, replacing any existing file.
func SyncFile(src string, dst string) error {
	slog.Info("compilation: SyncFile")
	if sameFile(src, dst) && !isSymlink(dst) {
		return nil
	}
	if common.IsSymlinkTo(dst, src) {
		return nil
	}
	_ = os.Remove(dst)
	if err := os.Symlink(src, dst); err != nil {
		slog.Warn("compilation: SyncFile symlink failed", "src", src, "dst", dst, "err", err)
		return fmt.Errorf("creating symlink %s: %w", dst, err)
	}
	return nil
}

func sameFile(firstPath string, secondPath string) bool {
	firstInfo, firstErr := os.Stat(firstPath)
	secondInfo, secondErr := os.Stat(secondPath)
	if firstErr != nil || secondErr != nil {
		return false
	}
	return os.SameFile(firstInfo, secondInfo)
}

func isSymlink(path string) bool {
	info, err := os.Lstat(path)
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeSymlink != 0
}

func sortedFilesWithExt(src string, ext string) ([]string, error) {
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: sortedFilesWithExt stat failed", "src", src, "err", err)
		return nil, fmt.Errorf("stat %s: %w", src, err)
	}
	files, err := filepath.Glob(filepath.Join(src, "*"+ext))
	if err != nil {
		return nil, fmt.Errorf("globbing files in %s: %w", src, err)
	}
	sort.Strings(files)
	return files, nil
}

func stripFrontmatter(content string) (string, error) {
	_, body, err := parseFrontmatter(content)
	return body, err
}

func renderCommandAsSkill(skillName string, body string) (string, error) {
	trimmedBody := strings.TrimSpace(body)
	description := fmt.Sprintf(
		"Run the /%s command workflow from the dotfiles agent command library when the user explicitly asks for /%s or mentions this command by name.",
		skillName,
		skillName,
	)
	frontmatter, err := renderFrontmatter(frontmatterMetadata{
		Name:        "cursor-command-" + skillName,
		Description: description,
		ApplyTo:     "",
	})
	if err != nil {
		return "", err
	}
	return frontmatter + "\n" + GeneratedAgentHTMLMarker + "\n\n" + trimmedBody + "\n", nil
}

func renderCopilotInstruction(baseName string, frontmatter agentRuleFrontmatter, body string) (string, error) {
	applyTo := strings.TrimSpace(frontmatter.Globs)
	if applyTo == "" && frontmatter.AlwaysApply {
		applyTo = "**/*"
	}

	metadata := frontmatterMetadata{
		Name:        baseName,
		Description: "",
		ApplyTo:     applyTo,
	}
	if description := strings.TrimSpace(frontmatter.Description); description != "" {
		metadata.Description = description
	}
	renderedFrontmatter, err := renderFrontmatter(metadata)
	if err != nil {
		return "", err
	}
	return renderedFrontmatter + "\n" + GeneratedAgentHTMLMarker + "\n\n" + strings.TrimSpace(body) + "\n", nil
}

func renderCopilotPrompt(baseName string, content string) (string, error) {
	frontmatter, body, err := parseFrontmatter(content)
	if err != nil {
		return "", err
	}
	description := strings.TrimSpace(frontmatter.Description)
	if description == "" {
		description = firstMarkdownHeading(body)
	}
	if description == "" {
		description = fmt.Sprintf("Run the %s workflow.", baseName)
	}

	renderedFrontmatter, renderErr := renderFrontmatter(frontmatterMetadata{
		Name:        baseName,
		Description: description,
		ApplyTo:     "",
	})
	if renderErr != nil {
		return "", renderErr
	}
	return renderedFrontmatter + "\n" + GeneratedAgentHTMLMarker + "\n\n" + strings.TrimSpace(body) + "\n", nil
}

func parseFrontmatter(content string) (agentRuleFrontmatter, string, error) {
	var values agentRuleFrontmatter
	if !strings.HasPrefix(content, "---\n") {
		return values, content, nil
	}
	endMarker := "\n---\n"
	frontmatterEnd := strings.Index(content[4:], endMarker)
	if frontmatterEnd == -1 {
		return values, content, nil
	}

	rawFrontmatter := content[4 : 4+frontmatterEnd]
	if err := yaml.Unmarshal([]byte(rawFrontmatter), &values); err != nil {
		slog.Warn("compilation: parseFrontmatter yaml failed", "err", err)
		return values, content, fmt.Errorf("parsing frontmatter: %w", err)
	}

	bodyStart := 4 + frontmatterEnd + len(endMarker)
	return values, content[bodyStart:], nil
}

func firstMarkdownHeading(content string) string {
	for line := range strings.SplitSeq(content, "\n") {
		trimmedLine := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmedLine, "#") {
			continue
		}
		return strings.TrimSpace(strings.TrimLeft(trimmedLine, "#"))
	}
	return ""
}

func renderFrontmatter(metadata frontmatterMetadata) (string, error) {
	content, err := yaml.Marshal(metadata)
	if err != nil {
		slog.Warn("compilation: renderFrontmatter yaml failed", "err", err)
		return "", fmt.Errorf("marshaling frontmatter: %w", err)
	}
	return "---\n" + string(content) + "---\n", nil
}

func writeFileIfChanged(path string, content []byte) error {
	cleanPath := filepath.Clean(path)
	slog.Info("compilation: writeFileIfChanged")
	if existing, err := os.ReadFile(cleanPath); err == nil {
		if bytes.Equal(existing, content) {
			return nil
		}
		if HasGeneratedMarker(string(content)) && !HasGeneratedMarker(string(existing)) && strings.TrimSpace(string(existing)) != "" {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(cleanPath), 0o755); err != nil {
		slog.Warn("compilation: writeFileIfChanged mkdir failed", "path", path, "err", err)
		return fmt.Errorf("creating directory %s: %w", filepath.Dir(cleanPath), err)
	}
	if err := os.WriteFile(cleanPath, content, 0o600); err != nil {
		slog.Warn("compilation: writeFileIfChanged write failed", "path", path, "err", err)
		return fmt.Errorf("writing file %s: %w", path, err)
	}
	return nil
}

func removeMissingManagedSkillDirs(dst string, managedPrefix string, activeDirs map[string]struct{}) error {
	slog.Info("compilation: removeMissingManagedSkillDirs")
	entries, err := os.ReadDir(dst)
	if err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: removeMissingManagedSkillDirs ReadDir failed", "dst", dst, "err", err)
		return fmt.Errorf("read dir %s: %w", dst, err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if !strings.HasPrefix(entry.Name(), managedPrefix) {
			continue
		}
		if _, ok := activeDirs[entry.Name()]; ok {
			continue
		}
		if err := os.RemoveAll(filepath.Join(dst, entry.Name())); err != nil {
			return fmt.Errorf("removing directory %s: %w", filepath.Join(dst, entry.Name()), err)
		}
	}
	return nil
}

func removeMissingManagedFiles(dst string, ext string, activeFiles map[string]struct{}) error {
	slog.Info("compilation: removeMissingManagedFiles")
	entries, err := os.ReadDir(dst)
	if err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: removeMissingManagedFiles ReadDir failed", "dst", dst, "err", err)
		return fmt.Errorf("read dir %s: %w", dst, err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ext) {
			continue
		}
		if _, ok := activeFiles[entry.Name()]; ok {
			continue
		}
		path := filepath.Join(dst, entry.Name())
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			continue
		}
		if !HasGeneratedMarker(string(content)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing file %s: %w", path, err)
		}
	}
	return nil
}
