package compilation

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"goodkind.io/.dotfiles/internal/cmdexec"
	"goodkind.io/.dotfiles/internal/prefercache"
	"goodkind.io/.dotfiles/internal/runner"
	"goodkind.io/.dotfiles/internal/sync/common"
	"goodkind.io/.dotfiles/internal/telemetry"
	"gopkg.in/yaml.v3"
)

const (
	AgentSourceDirName         = ".agents"
	CursorCompatibilityDirName = ".cursor"
	GeneratedAgentMarker       = "<!-- Generated by dotfiles from .agents. Do not edit this file directly. -->"
	GeneratedCursorMarker      = "<!-- Generated by dotfiles from .cursor. Do not edit this file directly. -->"
)

type AgentSourcePaths struct {
	Root     string
	Rules    string
	Commands string
	Skills   string
}

type agentRuleFrontmatter struct {
	Description string `yaml:"description,omitempty"`
	Globs       string `yaml:"globs,omitempty"`
	AlwaysApply bool   `yaml:"alwaysApply,omitempty"`
}

type copilotInstructionFrontmatter struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description,omitempty"`
	ApplyTo     string `yaml:"applyTo,omitempty"`
}

type copilotPromptFrontmatter struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

type commandSkillFrontmatter struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description"`
}

func ResolveAgentSource(dotfiles string) AgentSourcePaths {
	root := filepath.Join(dotfiles, AgentSourceDirName)
	if _, err := os.Stat(root); err != nil {
		compatibilityRoot := filepath.Join(dotfiles, CursorCompatibilityDirName)
		if _, compatibilityErr := os.Stat(compatibilityRoot); compatibilityErr == nil {
			root = compatibilityRoot
		}
	}

	return AgentSourcePaths{
		Root:     root,
		Rules:    filepath.Join(root, "rules"),
		Commands: filepath.Join(root, "commands"),
		Skills:   filepath.Join(root, "skills"),
	}
}

func EnsureCursorCompatibilityLink(dotfiles string) error {
	agentsRoot := filepath.Join(dotfiles, AgentSourceDirName)
	if _, err := os.Stat(agentsRoot); err != nil {
		return nil
	}

	cursorPath := filepath.Join(dotfiles, CursorCompatibilityDirName)
	info, err := os.Lstat(cursorPath)
	if err != nil {
		if os.IsNotExist(err) {
			return os.Symlink(AgentSourceDirName, cursorPath)
		}
		return err
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return fmt.Errorf("%s exists and is not a symlink", cursorPath)
	}

	linkTarget, err := os.Readlink(cursorPath)
	if err != nil {
		return err
	}
	if !filepath.IsAbs(linkTarget) {
		linkTarget = filepath.Join(filepath.Dir(cursorPath), linkTarget)
	}
	if filepath.Clean(linkTarget) != filepath.Clean(agentsRoot) {
		return fmt.Errorf("%s points to %s, expected %s", cursorPath, linkTarget, agentsRoot)
	}
	return nil
}

func HasGeneratedMarker(content string) bool {
	return strings.Contains(content, GeneratedAgentMarker) || strings.Contains(content, GeneratedCursorMarker)
}

func CompileZshFiles(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	dirs := []string{
		filepath.Join(dotfiles, "zshrc"),
		filepath.Join(dotfiles, "lib", "zinit"),
		filepath.Join(dotfiles, "lib", "zsh-defer"),
		filepath.Join(dotfiles, "home"),
		filepath.Join(dotfiles, "bin"),
	}
	for _, dir := range dirs {
		_ = filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if entry.IsDir() {
				return nil
			}
			name := filepath.Base(path)
			if !(strings.HasSuffix(name, ".zsh") || name == ".zshrc") {
				return nil
			}
			compiled := path + ".zwc"
			if NeedsCompile(path, compiled) {
				_ = cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", fmt.Sprintf("zcompile %q", path))
			}
			return nil
		})
	}
	return nil
}

func NeedsCompile(source string, target string) bool {
	sourceInfo, err := os.Stat(source)
	if err != nil {
		return false
	}
	targetInfo, err := os.Stat(target)
	if err != nil {
		return true
	}
	return sourceInfo.ModTime().After(targetInfo.ModTime())
}

func RebuildZcompdump(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	_ = os.RemoveAll(filepath.Join(os.Getenv("HOME"), ".zcompdump"))
	if !runner.HasCommand("zsh") {
		return nil
	}
	fpath := filepath.Join(dotfiles, "zshrc", "completions")
	return cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", fmt.Sprintf("fpath=(\"%s\" $fpath)\nautoload -Uz compinit\ncompinit -d ~/.zcompdump\nzcompile ~/.zcompdump\n", fpath))
}

func RebuildPreferCache(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	return prefercache.Rebuild(ctx, dotfiles, false, logger)
}

func CreateHushLogin(_ context.Context, _ *telemetry.Logger) error {
	path := filepath.Join(os.Getenv("HOME"), ".hushlogin")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return common.Touch(path)
}

func SyncRulesFromDir(src string, dst string) error {
	if _, err := os.Stat(src); err != nil {
		return nil
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := filepath.Glob(filepath.Join(src, "*.mdc"))
	if err != nil {
		return nil
	}
	for _, file := range entries {
		target := filepath.Join(dst, filepath.Base(file))
		if err := SyncFile(file, target); err != nil {
			return err
		}
	}
	return nil
}

func SyncRulesFromDirAsMd(src string, dst string) error {
	if _, err := os.Stat(src); err != nil {
		return nil
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := filepath.Glob(filepath.Join(src, "*.mdc"))
	if err != nil {
		return nil
	}
	for _, file := range entries {
		base := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		target := filepath.Join(dst, base+".md")
		if err := SyncFile(file, target); err != nil {
			return err
		}
	}
	return nil
}

func RenderRulesAsInstructionDoc(src string, dst string, title string) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return nil
	}
	if len(files) == 0 {
		return nil
	}

	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	builder.WriteString(GeneratedAgentMarker)
	builder.WriteString("\n\n")

	for index, file := range files {
		if index > 0 {
			builder.WriteString("\n\n")
		}
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		builder.WriteString("## ")
		builder.WriteString(baseName)
		builder.WriteString("\n\n")

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		body, stripErr := stripFrontmatter(string(content))
		if stripErr != nil {
			return stripErr
		}
		body = strings.TrimSpace(body)
		builder.WriteString(body)
		builder.WriteString("\n")
	}

	return writeFileIfChanged(dst, []byte(builder.String()))
}

func RenderCopilotInstructionFiles(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}

	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := baseName + ".instructions.md"
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		frontmatter, body, parseErr := parseFrontmatter(string(content))
		if parseErr != nil {
			return parseErr
		}
		rendered, renderErr := renderCopilotInstruction(baseName, frontmatter, body)
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(dst, targetName), []byte(rendered)); err != nil {
			return err
		}
	}

	return removeMissingManagedFiles(dst, ".instructions.md", activeFiles)
}

func RenderCopilotPromptFiles(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".md")
	if err != nil {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}

	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := baseName + ".prompt.md"
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		rendered, renderErr := renderCopilotPrompt(baseName, string(content))
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(dst, targetName), []byte(rendered)); err != nil {
			return err
		}
	}

	return removeMissingManagedFiles(dst, ".prompt.md", activeFiles)
}

func SyncCommandFilesAsSkillDirs(src string, dst string, managedPrefix string) error {
	files, err := sortedFilesWithExt(src, ".md")
	if err != nil {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}

	activeDirs := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		dirName := managedPrefix + baseName
		activeDirs[dirName] = struct{}{}

		targetDir := filepath.Join(dst, dirName)
		if err := os.MkdirAll(targetDir, 0o755); err != nil {
			return err
		}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			return readErr
		}
		skillContent, renderErr := renderCommandAsSkill(baseName, string(content))
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(targetDir, "SKILL.md"), []byte(skillContent)); err != nil {
			return err
		}
	}

	return removeMissingManagedSkillDirs(dst, managedPrefix, activeDirs)
}

func SyncFilesToDir(src string, dst string) error {
	if _, err := os.Stat(src); err != nil {
		return nil
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if err := SyncFile(filepath.Join(src, entry.Name()), filepath.Join(dst, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func SyncSkillDirs(src string, dst string) error {
	if _, err := os.Stat(src); err != nil {
		return nil
	}
	if sameFile(src, dst) {
		return nil
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		source := filepath.Join(src, entry.Name())
		target := filepath.Join(dst, entry.Name())
		if sameFile(source, target) && !isSymlink(target) {
			continue
		}
		if common.IsSymlinkTo(target, source) {
			continue
		}
		_ = os.Remove(target)
		if err := os.Symlink(source, target); err != nil {
			return err
		}
	}
	return nil
}

func SyncFile(src string, dst string) error {
	if sameFile(src, dst) && !isSymlink(dst) {
		return nil
	}
	if common.IsSymlinkTo(dst, src) {
		return nil
	}
	_ = os.Remove(dst)
	return os.Symlink(src, dst)
}

func sameFile(firstPath string, secondPath string) bool {
	firstInfo, firstErr := os.Stat(firstPath)
	secondInfo, secondErr := os.Stat(secondPath)
	if firstErr != nil || secondErr != nil {
		return false
	}
	return os.SameFile(firstInfo, secondInfo)
}

func isSymlink(path string) bool {
	info, err := os.Lstat(path)
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeSymlink != 0
}

func sortedFilesWithExt(src string, ext string) ([]string, error) {
	if _, err := os.Stat(src); err != nil {
		return nil, nil
	}
	files, err := filepath.Glob(filepath.Join(src, "*"+ext))
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	return files, nil
}

func stripFrontmatter(content string) (string, error) {
	_, body, err := parseFrontmatter(content)
	return body, err
}

func renderCommandAsSkill(skillName string, body string) (string, error) {
	trimmedBody := strings.TrimSpace(body)
	description := fmt.Sprintf(
		"Run the %s workflow from the dotfiles agent command library when the user explicitly asks for that command or checklist.",
		skillName,
	)
	frontmatter, err := renderFrontmatter(commandSkillFrontmatter{
		Name:        skillName,
		Description: description,
	})
	if err != nil {
		return "", err
	}
	return frontmatter + "\n" + GeneratedAgentMarker + "\n\n" + trimmedBody + "\n", nil
}

func renderCopilotInstruction(baseName string, frontmatter agentRuleFrontmatter, body string) (string, error) {
	applyTo := strings.TrimSpace(frontmatter.Globs)
	if applyTo == "" && frontmatter.AlwaysApply {
		applyTo = "**/*"
	}

	metadata := copilotInstructionFrontmatter{
		Name:    baseName,
		ApplyTo: applyTo,
	}
	if description := strings.TrimSpace(frontmatter.Description); description != "" {
		metadata.Description = description
	}
	renderedFrontmatter, err := renderFrontmatter(metadata)
	if err != nil {
		return "", err
	}
	return renderedFrontmatter + "\n" + GeneratedAgentMarker + "\n\n" + strings.TrimSpace(body) + "\n", nil
}

func renderCopilotPrompt(baseName string, content string) (string, error) {
	frontmatter, body, err := parseFrontmatter(content)
	if err != nil {
		return "", err
	}
	description := strings.TrimSpace(frontmatter.Description)
	if description == "" {
		description = firstMarkdownHeading(body)
	}
	if description == "" {
		description = fmt.Sprintf("Run the %s workflow.", baseName)
	}

	renderedFrontmatter, renderErr := renderFrontmatter(copilotPromptFrontmatter{
		Name:        baseName,
		Description: description,
	})
	if renderErr != nil {
		return "", renderErr
	}
	return renderedFrontmatter + "\n" + GeneratedAgentMarker + "\n\n" + strings.TrimSpace(body) + "\n", nil
}

func parseFrontmatter(content string) (agentRuleFrontmatter, string, error) {
	var values agentRuleFrontmatter
	if !strings.HasPrefix(content, "---\n") {
		return values, content, nil
	}
	endMarker := "\n---\n"
	frontmatterEnd := strings.Index(content[4:], endMarker)
	if frontmatterEnd == -1 {
		return values, content, nil
	}

	rawFrontmatter := content[4 : 4+frontmatterEnd]
	if err := yaml.Unmarshal([]byte(rawFrontmatter), &values); err != nil {
		return values, content, err
	}

	bodyStart := 4 + frontmatterEnd + len(endMarker)
	return values, content[bodyStart:], nil
}

func firstMarkdownHeading(content string) string {
	for _, line := range strings.Split(content, "\n") {
		trimmedLine := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmedLine, "#") {
			continue
		}
		return strings.TrimSpace(strings.TrimLeft(trimmedLine, "#"))
	}
	return ""
}

func renderFrontmatter(metadata interface{}) (string, error) {
	content, err := yaml.Marshal(metadata)
	if err != nil {
		return "", err
	}
	return "---\n" + string(content) + "---\n", nil
}

func writeFileIfChanged(path string, content []byte) error {
	if existing, err := os.ReadFile(path); err == nil {
		if bytes.Equal(existing, content) {
			return nil
		}
		if HasGeneratedMarker(string(content)) && !HasGeneratedMarker(string(existing)) {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o644)
}

func removeMissingManagedSkillDirs(dst string, managedPrefix string, activeDirs map[string]struct{}) error {
	entries, err := os.ReadDir(dst)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if !strings.HasPrefix(entry.Name(), managedPrefix) {
			continue
		}
		if _, ok := activeDirs[entry.Name()]; ok {
			continue
		}
		if err := os.RemoveAll(filepath.Join(dst, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func removeMissingManagedFiles(dst string, ext string, activeFiles map[string]struct{}) error {
	entries, err := os.ReadDir(dst)
	if err != nil {
		return nil
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ext) {
			continue
		}
		if _, ok := activeFiles[entry.Name()]; ok {
			continue
		}
		path := filepath.Join(dst, entry.Name())
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			continue
		}
		if !HasGeneratedMarker(string(content)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}
