// Package compilation implements zsh file compilation during sync.
package compilation

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"goodkind.io/.dotfiles/internal/cmdexec"
	"goodkind.io/.dotfiles/internal/prefercache"
	"goodkind.io/.dotfiles/internal/runner"
	"goodkind.io/.dotfiles/internal/sync/common"
	"goodkind.io/.dotfiles/internal/telemetry"
	"gopkg.in/yaml.v3"
)

const (
	// CorpusDirName is the name of the agent corpus source directory within dotfiles.
	CorpusDirName = "corpus"
	// GeneratedAgentMarker is the plain-text marker embedded in files generated from corpus.
	GeneratedAgentMarker = "# Generated by dotfiles from corpus. Do not edit this file directly."
	// GeneratedAgentHTMLMarker is the HTML comment marker embedded in files generated from corpus.
	GeneratedAgentHTMLMarker = "<!-- Generated by dotfiles from corpus. Do not edit this file directly. -->"
)

// CorpusPaths holds resolved paths for the agent corpus source directory tree.
type CorpusPaths struct {
	Root   string
	Rules  string
	Skills string
}

type agentRuleFrontmatter struct {
	Description string `yaml:"description,omitempty"`
	Globs       string `yaml:"globs,omitempty"`
	AlwaysApply bool   `yaml:"alwaysApply,omitempty"`
}

type frontmatterMetadata struct {
	Name        string `yaml:"name,omitempty"`
	Description string `yaml:"description,omitempty"`
	ApplyTo     string `yaml:"applyTo,omitempty"`
}

// ResolveCorpusSource returns the CorpusPaths for the given dotfiles root.
func ResolveCorpusSource(dotfiles string) CorpusPaths {
	root := filepath.Join(dotfiles, CorpusDirName)
	return CorpusPaths{
		Root:   root,
		Rules:  filepath.Join(root, "rules"),
		Skills: filepath.Join(root, "skills"),
	}
}

// HasGeneratedMarker reports whether content contains any generated-file marker.
func HasGeneratedMarker(content string) bool {
	return strings.Contains(content, GeneratedAgentMarker) || strings.Contains(content, GeneratedAgentHTMLMarker)
}

// CompileZshFiles compiles all .zsh files found under standard dotfiles directories.
func CompileZshFiles(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	dirs := []string{
		filepath.Join(dotfiles, "zshrc"),
		filepath.Join(dotfiles, "lib", "zinit"),
		filepath.Join(dotfiles, "lib", "zsh-defer"),
		filepath.Join(dotfiles, "home"),
		filepath.Join(dotfiles, "bin"),
	}
	for _, dir := range dirs {
		_ = filepath.WalkDir(dir, func(path string, entry os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if entry.IsDir() {
				return nil
			}
			name := filepath.Base(path)
			if !strings.HasSuffix(name, ".zsh") && name != ".zshrc" {
				return nil
			}
			compiled := path + ".zwc"
			if NeedsCompile(path, compiled) {
				_ = cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", fmt.Sprintf("zcompile %q", path))
			}
			return nil
		})
	}
	return nil
}

// NeedsCompile reports whether source is newer than target and requires recompilation.
func NeedsCompile(source string, target string) bool {
	sourceInfo, err := os.Stat(source)
	if err != nil {
		return false
	}
	targetInfo, err := os.Stat(target)
	if err != nil {
		return true
	}
	return sourceInfo.ModTime().After(targetInfo.ModTime())
}

// RebuildZcompdump removes and regenerates the zsh completion dump file.
func RebuildZcompdump(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	slog.InfoContext(ctx, "compilation: RebuildZcompdump")
	_ = os.RemoveAll(filepath.Clean(filepath.Join(os.Getenv("HOME"), ".zcompdump")))
	if !runner.HasCommand("zsh") {
		return nil
	}
	fpath := filepath.Join(dotfiles, "zshrc", "completions")
	zcompdump := filepath.Join(os.Getenv("HOME"), ".zcompdump")
	autoloadCmd := fmt.Sprintf("fpath=(\"%s\" $fpath)\nautoload -Uz compinit\n", fpath)
	if err := cmdexec.RunWithLogger(ctx, logger, "zsh", "-c", autoloadCmd+"compinit -d "+zcompdump+"\nzcompile "+zcompdump+"\n"); err != nil {
		slog.ErrorContext(ctx, "rebuild zsh completions", "err", err)
		return fmt.Errorf("rebuild zsh completions: %w", err)
	}
	return nil
}

// RebuildPreferCache rebuilds the prefer-alias cache for the dotfiles installation.
func RebuildPreferCache(ctx context.Context, dotfiles string, logger *telemetry.Logger) error {
	if err := prefercache.Rebuild(ctx, dotfiles, false, logger); err != nil {
		slog.WarnContext(ctx, "compilation: RebuildPreferCache failed", "err", err)
		return fmt.Errorf("rebuilding prefer cache: %w", err)
	}
	return nil
}

// CreateHushLogin creates the ~/.hushlogin file if it does not already exist.
func CreateHushLogin(ctx context.Context, _ *telemetry.Logger) error {
	path := filepath.Join(os.Getenv("HOME"), ".hushlogin")
	if _, err := os.Stat(filepath.Clean(path)); err == nil {
		return nil
	}
	if err := common.Touch(path); err != nil {
		slog.WarnContext(ctx, "compilation: CreateHushLogin touch failed", "err", err)
		return fmt.Errorf("creating hushlogin: %w", err)
	}
	return nil
}

// RuleRenderStyle describes how generated rule files reference generated skills.
type RuleRenderStyle struct {
	// SkillsRelDir is the relative directory from the rendered rule location to generated skill directories.
	SkillsRelDir string
}

// RenderRuleFiles writes each .mdc rule file from src into dst as a marker-stamped
// generated file with the given extension (for example ".mdc" or ".md").
func RenderRuleFiles(src string, dst string, ext string, style RuleRenderStyle) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		base := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := base + ext
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderRuleFiles read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		rendered, renderErr := renderRuleTemplate(string(content), style, filepath.Base(file))
		if renderErr != nil {
			return renderErr
		}
		target := filepath.Join(dst, targetName)
		if isSymlink(target) {
			_ = os.Remove(target)
		}
		if err := writeFileIfChanged(target, []byte(injectSkillMarker(rendered))); err != nil {
			return err
		}
	}
	return removeMissingManagedFiles(dst, ext, activeFiles)
}

// ruleTemplateData exposes skill reference helpers to a rule template as the
// "{{.Skill \"name\"}}" method for the active RuleRenderStyle.
type ruleTemplateData struct {
	style   RuleRenderStyle
	execErr *error
}

// Skill renders a single skill link for the active style.
func (d ruleTemplateData) Skill(name string) string {
	if d.style.SkillsRelDir == "" {
		if d.execErr != nil {
			*d.execErr = fmt.Errorf("skill link %q requires skill_dest in manifest", name)
		}
		return ""
	}
	return renderSkillLink(d.style, name)
}

func renderRuleTemplate(content string, style RuleRenderStyle, name string) (string, error) {
	if !strings.Contains(content, "{{") {
		return content, nil
	}
	var execErr error
	parsed, err := template.New(name).Parse(content)
	if err != nil {
		slog.Warn("compilation: renderRuleTemplate parse failed", "name", name, "err", err)
		return "", fmt.Errorf("parsing rule template %s: %w", name, err)
	}
	buf := bytes.NewBuffer(nil)
	if err := parsed.Execute(buf, ruleTemplateData{style: style, execErr: &execErr}); err != nil {
		slog.Warn("compilation: renderRuleTemplate execute failed", "name", name, "err", err)
		return "", fmt.Errorf("executing rule template %s: %w", name, err)
	}
	if execErr != nil {
		return "", execErr
	}
	return buf.String(), nil
}

func renderSkillLink(style RuleRenderStyle, name string) string {
	skillPath := filepath.ToSlash(filepath.Join(style.SkillsRelDir, name, "SKILL.md"))
	return fmt.Sprintf("[%s](%s)", name, skillPath)
}

// RenderRulesAsInstructionDoc concatenates .mdc rule files from src into a single markdown document at dst.
func RenderRulesAsInstructionDoc(src string, dst string, title string, style RuleRenderStyle) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return nil
	}

	var builder strings.Builder
	builder.WriteString("# ")
	builder.WriteString(title)
	builder.WriteString("\n\n")
	builder.WriteString(GeneratedAgentHTMLMarker)
	builder.WriteString("\n\n")

	for index, file := range files {
		if index > 0 {
			builder.WriteString("\n\n")
		}
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		builder.WriteString("## ")
		builder.WriteString(baseName)
		builder.WriteString("\n\n")

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderRulesAsInstructionDoc read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		body, stripErr := stripFrontmatter(string(content))
		if stripErr != nil {
			return stripErr
		}
		rendered, renderErr := renderRuleTemplate(strings.TrimSpace(body), style, filepath.Base(file))
		if renderErr != nil {
			return renderErr
		}
		builder.WriteString(rendered)
		builder.WriteString("\n")
	}

	return writeFileIfChanged(dst, []byte(builder.String()))
}

// RenderCopilotInstructionFiles renders .mdc rule files from src as .instructions.md files in dst.
func RenderCopilotInstructionFiles(src string, dst string, style RuleRenderStyle) error {
	files, err := sortedFilesWithExt(src, ".mdc")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		slog.Warn("compilation: RenderCopilotInstructionFiles mkdir failed", "dst", dst, "err", err)
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}

	activeFiles := make(map[string]struct{}, len(files))
	for _, file := range files {
		baseName := strings.TrimSuffix(filepath.Base(file), filepath.Ext(file))
		targetName := baseName + ".instructions.md"
		activeFiles[targetName] = struct{}{}

		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderCopilotInstructionFiles read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		frontmatter, body, parseErr := parseFrontmatter(string(content))
		if parseErr != nil {
			return parseErr
		}
		renderedBody, renderErr := renderRuleTemplate(strings.TrimSpace(body), style, filepath.Base(file))
		if renderErr != nil {
			return renderErr
		}
		rendered, renderErr := renderCopilotInstruction(baseName, frontmatter, renderedBody)
		if renderErr != nil {
			return renderErr
		}
		if err := writeFileIfChanged(filepath.Join(dst, targetName), []byte(rendered)); err != nil {
			return err
		}
	}

	return removeMissingManagedFiles(dst, ".instructions.md", activeFiles)
}

// RenderCodexRules concatenates .rules files from src into a single Codex rules file at dst.
func RenderCodexRules(src string, dst string) error {
	files, err := sortedFilesWithExt(src, ".rules")
	if err != nil {
		return err
	}

	var builder strings.Builder
	builder.WriteString(GeneratedAgentMarker)
	builder.WriteString("\n")
	for _, file := range files {
		content, readErr := os.ReadFile(file)
		if readErr != nil {
			slog.Warn("compilation: RenderCodexRules read failed", "file", file, "err", readErr)
			return fmt.Errorf("reading file %s: %w", file, readErr)
		}
		trimmedContent := strings.TrimSpace(string(content))
		if trimmedContent == "" {
			continue
		}
		builder.WriteString("\n# ")
		builder.WriteString(filepath.Base(file))
		builder.WriteString("\n")
		builder.WriteString(trimmedContent)
		builder.WriteString("\n")
	}
	return writeFileIfChanged(dst, []byte(builder.String()))
}

// SkillRefStyle describes how a provider's skill files reference rule documents.
type SkillRefStyle struct {
	// RulesRelDir is the relative directory from a skill directory to the rule files.
	RulesRelDir string
	// RuleExt is the rule file extension including the leading dot.
	RuleExt string
	// SingleDocAnchor links rule references to one instruction document using a section anchor.
	SingleDocAnchor bool
	// DocRelPath is the relative path to the single instruction document when SingleDocAnchor is true.
	DocRelPath string
}

var (
	// SkillRefMDC links rule references to sibling .mdc rule files (Cursor and the shared agents mirror).
	SkillRefMDC = SkillRefStyle{RulesRelDir: "../../rules", RuleExt: ".mdc", SingleDocAnchor: false, DocRelPath: ""}
	// SkillRefMD links rule references to sibling .md rule files (Claude).
	SkillRefMD = SkillRefStyle{RulesRelDir: "../../rules", RuleExt: ".md", SingleDocAnchor: false, DocRelPath: ""}
	// SkillRefInstructions links rule references to Copilot .instructions.md files.
	SkillRefInstructions = SkillRefStyle{RulesRelDir: "../../instructions", RuleExt: ".instructions.md", SingleDocAnchor: false, DocRelPath: ""}
	// SkillRefCodexDoc links rule references to sections of the Codex AGENTS.md document.
	SkillRefCodexDoc = SkillRefStyle{RulesRelDir: "", RuleExt: "", SingleDocAnchor: true, DocRelPath: "../../AGENTS.md"}
)

// RenderSkillDirs renders skill directories from src into dst, expanding rule-reference tokens for refStyle.
func RenderSkillDirs(src string, dst string, refStyle SkillRefStyle) error {
	slog.Info("compilation: RenderSkillDirs")
	if _, err := os.Stat(src); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		slog.Warn("compilation: RenderSkillDirs stat failed", "src", src, "err", err)
		return fmt.Errorf("stat %s: %w", src, err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	ruleNames, err := ruleBaseNames(filepath.Join(filepath.Dir(src), "rules"))
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		slog.Warn("compilation: RenderSkillDirs ReadDir failed", "src", src, "err", err)
		return fmt.Errorf("read dir %s: %w", src, err)
	}
	activeSkills := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		activeSkills[entry.Name()] = struct{}{}
		source := filepath.Join(src, entry.Name())
		target := filepath.Join(dst, entry.Name())
		if isSymlink(target) {
			_ = os.Remove(target)
		}
		if err := renderSkillDir(source, target, refStyle, ruleNames); err != nil {
			return err
		}
	}
	return removeMissingManagedSkillDirs(dst, activeSkills)
}

func renderSkillDir(src string, dst string, refStyle SkillRefStyle, ruleNames []string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		slog.Warn("compilation: renderSkillDir ReadDir failed", "src", src, "err", err)
		return fmt.Errorf("read dir %s: %w", src, err)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return fmt.Errorf("creating directory %s: %w", dst, err)
	}
	for _, entry := range entries {
		source := filepath.Join(src, entry.Name())
		target := filepath.Join(dst, entry.Name())
		if entry.IsDir() {
			if err := renderSkillDir(source, target, refStyle, ruleNames); err != nil {
				return err
			}
			continue
		}
		content, readErr := os.ReadFile(source)
		if readErr != nil {
			slog.Warn("compilation: renderSkillDir read failed", "path", source, "err", readErr)
			return fmt.Errorf("reading file %s: %w", source, readErr)
		}
		outputName := entry.Name()
		output := content
		if base, ok := strings.CutSuffix(entry.Name(), ".tmpl"); ok {
			outputName = base
			rendered, tmplErr := renderSkillTemplate(string(content), refStyle, ruleNames, entry.Name())
			if tmplErr != nil {
				return tmplErr
			}
			output = []byte(rendered)
		}
		target = filepath.Join(dst, outputName)
		if isSymlink(target) {
			_ = os.Remove(target)
		}
		if err := writeFileIfChanged(target, output); err != nil {
			return err
		}
	}
	return nil
}

// skillTemplateData exposes the rule reference helpers to a skill template as the
// "{{.Rules}}" and "{{.Rule \"name\"}}" methods for the active refStyle.
type skillTemplateData struct {
	style     SkillRefStyle
	ruleNames []string
}

// Rules renders the full rule list for the active style.
func (d skillTemplateData) Rules() string { return renderRulesList(d.style, d.ruleNames) }

// Rule renders a single rule link for the active style.
func (d skillTemplateData) Rule(name string) string { return renderRuleLink(d.style, name) }

// renderSkillTemplate renders one skill template through text/template.
func renderSkillTemplate(content string, refStyle SkillRefStyle, ruleNames []string, name string) (string, error) {
	parsed, err := template.New(name).Parse(content)
	if err != nil {
		slog.Warn("compilation: renderSkillTemplate parse failed", "name", name, "err", err)
		return "", fmt.Errorf("parsing skill template %s: %w", name, err)
	}
	buf := bytes.NewBuffer(nil)
	if err := parsed.Execute(buf, skillTemplateData{style: refStyle, ruleNames: ruleNames}); err != nil {
		slog.Warn("compilation: renderSkillTemplate execute failed", "name", name, "err", err)
		return "", fmt.Errorf("executing skill template %s: %w", name, err)
	}
	return injectSkillMarker(buf.String()), nil
}

func renderRuleLink(refStyle SkillRefStyle, name string) string {
	if refStyle.SingleDocAnchor {
		return fmt.Sprintf("[%s](%s#%s)", name, refStyle.DocRelPath, name)
	}
	fileName := name + refStyle.RuleExt
	return fmt.Sprintf("[%s](%s/%s)", fileName, refStyle.RulesRelDir, fileName)
}

func renderRulesList(refStyle SkillRefStyle, ruleNames []string) string {
	var builder strings.Builder
	for index, name := range ruleNames {
		if index > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString("- ")
		builder.WriteString(renderRuleLink(refStyle, name))
	}
	return builder.String()
}

func injectSkillMarker(content string) string {
	if HasGeneratedMarker(content) {
		return content
	}
	if strings.HasPrefix(content, "---\n") {
		endMarker := "\n---\n"
		frontmatterEnd := strings.Index(content[4:], endMarker)
		if frontmatterEnd != -1 {
			cut := 4 + frontmatterEnd + len(endMarker)
			return content[:cut] + "\n" + GeneratedAgentHTMLMarker + "\n" + content[cut:]
		}
	}
	return GeneratedAgentHTMLMarker + "\n\n" + content
}

func ruleBaseNames(rulesDir string) ([]string, error) {
	files, err := sortedFilesWithExt(rulesDir, ".mdc")
	if err != nil {
		return nil, err
	}
	names := make([]string, 0, len(files))
	for _, file := range files {
		names = append(names, strings.TrimSuffix(filepath.Base(file), filepath.Ext(file)))
	}
	return names, nil
}

func removeMissingManagedSkillDirs(dst string, activeSkills map[string]struct{}) error {
	slog.Info("compilation: removeMissingManagedSkillDirs")
	entries, err := os.ReadDir(dst)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		slog.Warn("compilation: removeMissingManagedSkillDirs ReadDir failed", "dst", dst, "err", err)
		return fmt.Errorf("read dir %s: %w", dst, err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if _, ok := activeSkills[name]; ok {
			continue
		}
		path := filepath.Join(dst, name)
		if isSymlink(path) {
			_ = os.Remove(path)
			continue
		}
		if !entry.IsDir() {
			continue
		}
		skillContent, readErr := os.ReadFile(filepath.Join(path, "SKILL.md"))
		if readErr != nil {
			continue
		}
		if !HasGeneratedMarker(string(skillContent)) {
			continue
		}
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("removing directory %s: %w", path, err)
		}
	}
	return nil
}

func isSymlink(path string) bool {
	info, err := os.Lstat(path)
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeSymlink != 0
}

func sortedFilesWithExt(src string, ext string) ([]string, error) {
	if _, err := os.Stat(src); err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: sortedFilesWithExt stat failed", "src", src, "err", err)
		return nil, fmt.Errorf("stat %s: %w", src, err)
	}
	files, err := filepath.Glob(filepath.Join(src, "*"+ext))
	if err != nil {
		return nil, fmt.Errorf("globbing files in %s: %w", src, err)
	}
	sort.Strings(files)
	return files, nil
}

func stripFrontmatter(content string) (string, error) {
	_, body, err := parseFrontmatter(content)
	return body, err
}

func renderCopilotInstruction(baseName string, frontmatter agentRuleFrontmatter, body string) (string, error) {
	applyTo := strings.TrimSpace(frontmatter.Globs)
	if applyTo == "" && frontmatter.AlwaysApply {
		applyTo = "**/*"
	}

	metadata := frontmatterMetadata{
		Name:        baseName,
		Description: "",
		ApplyTo:     applyTo,
	}
	if description := strings.TrimSpace(frontmatter.Description); description != "" {
		metadata.Description = description
	}
	renderedFrontmatter, err := renderFrontmatter(metadata)
	if err != nil {
		return "", err
	}
	return renderedFrontmatter + "\n" + GeneratedAgentHTMLMarker + "\n\n" + strings.TrimSpace(body) + "\n", nil
}

func parseFrontmatter(content string) (agentRuleFrontmatter, string, error) {
	var values agentRuleFrontmatter
	if !strings.HasPrefix(content, "---\n") {
		return values, content, nil
	}
	endMarker := "\n---\n"
	frontmatterEnd := strings.Index(content[4:], endMarker)
	if frontmatterEnd == -1 {
		return values, content, nil
	}

	rawFrontmatter := content[4 : 4+frontmatterEnd]
	if err := yaml.Unmarshal([]byte(rawFrontmatter), &values); err != nil {
		slog.Warn("compilation: parseFrontmatter yaml failed", "err", err)
		return values, content, fmt.Errorf("parsing frontmatter: %w", err)
	}

	bodyStart := 4 + frontmatterEnd + len(endMarker)
	return values, content[bodyStart:], nil
}

func renderFrontmatter(metadata frontmatterMetadata) (string, error) {
	content, err := yaml.Marshal(metadata)
	if err != nil {
		slog.Warn("compilation: renderFrontmatter yaml failed", "err", err)
		return "", fmt.Errorf("marshaling frontmatter: %w", err)
	}
	return "---\n" + string(content) + "---\n", nil
}

func writeFileIfChanged(path string, content []byte) error {
	cleanPath := filepath.Clean(path)
	slog.Info("compilation: writeFileIfChanged")
	if existing, err := os.ReadFile(cleanPath); err == nil {
		if bytes.Equal(existing, content) {
			return nil
		}
		if HasGeneratedMarker(string(content)) && !HasGeneratedMarker(string(existing)) && strings.TrimSpace(string(existing)) != "" {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(cleanPath), 0o755); err != nil {
		slog.Warn("compilation: writeFileIfChanged mkdir failed", "path", path, "err", err)
		return fmt.Errorf("creating directory %s: %w", filepath.Dir(cleanPath), err)
	}
	if err := os.WriteFile(cleanPath, content, 0o600); err != nil {
		slog.Warn("compilation: writeFileIfChanged write failed", "path", path, "err", err)
		return fmt.Errorf("writing file %s: %w", path, err)
	}
	return nil
}

func removeMissingManagedFiles(dst string, ext string, activeFiles map[string]struct{}) error {
	slog.Info("compilation: removeMissingManagedFiles")
	entries, err := os.ReadDir(dst)
	if err != nil && !os.IsNotExist(err) {
		slog.Warn("compilation: removeMissingManagedFiles ReadDir failed", "dst", dst, "err", err)
		return fmt.Errorf("read dir %s: %w", dst, err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if !strings.HasSuffix(entry.Name(), ext) {
			continue
		}
		if _, ok := activeFiles[entry.Name()]; ok {
			continue
		}
		path := filepath.Join(dst, entry.Name())
		content, readErr := os.ReadFile(path)
		if readErr != nil {
			continue
		}
		if !HasGeneratedMarker(string(content)) {
			continue
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing file %s: %w", path, err)
		}
	}
	return nil
}
