#!/usr/bin/env bash

if command -v fastfetch &> /dev/null; then
    fastfetch --config - <<'EOF'
{
  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
  "logo": {
    "type": "auto"
  },
  "display": {
    "separator": ": "
  },
  "modules": [
    "title",
    "separator",
    "os",
    "host",
    "kernel",
    "uptime",
    "packages",
    "terminal",
    "cpu",
    "gpu",
    "memory",
    "swap",
    "disk",
    "users",
    "battery"
  ]
}
EOF
fi