#!/usr/bin/env bash
# This script lists all bans and unbans from fail2ban
# It sometimes is not very accurate in calculating the still active bans
# Taken from: https://github.com/yboetz/motd/blob/master/50-fail2ban

if ! command -v fail2ban-client &> /dev/null; then
    # fail2ban is not installed
    exit 0
fi

logfile='/var/log/fail2ban.log*'

# Check if log files exist
if ! ls $logfile &>/dev/null; then
    exit 0
fi

mapfile -t lines < <(grep -hioP '(\[[a-z-]+\]) (ban|unban)' $logfile 2>/dev/null | sort | uniq -c)
jails=($(printf -- '%s\n' "${lines[@]}" | grep -oP '\[\K[^\]]+' | sort | uniq))

# Exit if no jails found
if [[ ${#jails[@]} -eq 0 ]]; then
    exit 0
fi

out=""
for jail in "${jails[@]}"; do
    bans=$(printf -- '%s\n' "${lines[@]}" | grep -iP "[[:digit:]]+ \[$jail\] ban" | awk '{print $1}')
    unbans=$(printf -- '%s\n' "${lines[@]}" | grep -iP "[[:digit:]]+ \[$jail\] unban" | awk '{print $1}')
    bans=${bans:-0} # default value
    unbans=${unbans:-0} # default value
    diff=$((bans-unbans))
    out+=$(printf "%s, %+3s bans, %+3s unbans, %+3s active" "$jail" "$bans" "$unbans" "$diff")"\n"
done

printf "\nfail2ban status (monthly):\n"
printf "$out" | column -ts $',' | sed -e 's/^/  /'

