name: CI

on:
  push:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go:
    uses: agoodkind/go-makefile/.github/workflows/_ci.yml@033f704db6d21ff71b25cd2299a457f4db78b5a2
    permissions:
      contents: read
      id-token: write
    with:
      apt_packages: zsh
      go_version_file: dots/go.mod
      submodules: recursive
      working_directory: dots
